# Generated by Django 5.2.8 on 2025-11-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/defult.png', upload_to='posts/images/'),
        ),
    ]
